name: 'Generate export plist file for iOS build'
description: 'Generate export plist file for iOS build'
inputs:
  method:
    description: 'Export method'
    default: ad-hoc
    required: true
  development-team-id:
    description: 'Development Team ID'
    required: true
  development-team-name:
    description: 'Development Team Name'
    required: true
  product-bundle-identifier:
    description: 'Product Bundle Identifier'
    required: true
  provisioning-profile-specifier:
    description: 'Provisioning Profile Specifier'
    required: true
  export-plist-path:
    description: 'Output path'
    required: true
runs:
  using: "composite"
  steps:
    - name: Upload dSYM artifact to crashlytics
      id: plist-generator
      run: |
        {
          printf '<?xml version="1.0" encoding="UTF-8"?>'
          printf '\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">'
          printf '\n<plist version="1.0">'
          printf '\n<dict>'
          printf '\n\t<key>method</key>'
          printf '\n\t<string>${{ inputs.method }}</string>'
          printf '\n\t<key>teamID</key>'
          printf '\n\t<string>${{ inputs.development-team-id }}</string>'
          printf '\n\t<key>compileBitcode</key>'
          printf '\n\t<false/>'
          printf '\n\t<key>uploadBitcode</key>'
          printf '\n\t<false/>'
          printf '\n\t<key>uploadSymbols</key>'
          printf '\n\t<true/>'
          printf '\n\t<key>signingStyle</key>'
          printf '\n\t<string>manual</string>'
          printf '\n\t<key>signingCertificate</key>'
          printf '\n\t<string>Apple Distribution: ${{ inputs.development-team-name }} (${{ inputs.development-team-id }})</string>'
          printf '\n\t<key>provisioningProfiles</key>'
          printf '\n\t<dict>'
          printf '\n\t\t<key>${{ inputs.product-bundle-identifier }}</key>'
          printf '\n\t\t<string>${{ inputs.provisioning-profile-specifier }}</string>'
          printf '\n\t</dict>'
          printf '\n</dict>'
          printf '\n</plist>'
        } > "${{ inputs.export-plist-path }}"
      shell: bash
